server:
  port: 9225

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/home/workpace/websocket/db/websocket
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:sql/create.sql
      mode: embedded

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
